# Generated by Django 5.2.1 on 2025-05-19 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_payment_model_course_price_enrollment_payment'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_model',
            field=models.CharField(choices=[('buy_first', 'Beli dulu baru enrol'), ('pay_for_exam', 'Enrol dulu, bayar saat ujian'), ('pay_for_certificate', 'Enrol & ujian dulu, bayar saat sertifikat'), ('free', 'Gratis')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'course', 'payment_model')},
        ),
    ]
