# Generated by Django 5.2.1 on 2025-06-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_model',
            field=models.CharField(choices=[('buy_first', 'Buy first, then enroll'), ('pay_for_exam', 'Enroll first, pay at exam'), ('pay_for_certificate', 'Enroll & take exam first, pay at certificate claim'), ('free', 'Free')], max_length=20),
        ),
    ]
