# Generated by Django 5.2.1 on 2025-06-17 05:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_coursesessionlog_location_city_and_more'),
        ('payments', '0006_alter_payment_payment_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='course_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.courseprice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='IDR', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Snapshot Discount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_ice_earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Snapshot ICE Earning'),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_partner_earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Snapshot Partner Earning'),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Snapshot PPN Value'),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Snapshot Normal Price'),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Snapshot Tax (%)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='snapshot_user_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Snapshot User Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_model',
            field=models.CharField(choices=[('buy_first', 'Buy first, then enroll'), ('pay_for_exam', 'Enroll first, pay at exam'), ('pay_for_certificate', 'Enroll & take exam first, pay at certificate claim'), ('free', 'Free')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
