# Generated by Django 5.2.1 on 2025-06-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_options_payment_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.transaction'),
        ),
    ]
