# Generated by Django 5.2.1 on 2025-10-02 09:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_remove_courseprice_unique_course_price_and_more'),
        ('payments', '0011_voucher_voucherusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Amount Paid (IDR)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_model',
            field=models.CharField(choices=[('free', 'Free'), ('buy_first', 'Buy First'), ('subscription', 'Subscription'), ('pay_for_exam', 'Pay for Exam'), ('pay_for_certificate', 'Pay for Certificate')], default='buy_first', max_length=50, verbose_name='Payment Model'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique ID from payment gateway or transaction reference', max_length=100, null=True, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'course', 'payment_model'], name='payments_pa_user_id_a82dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='isp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='linked_transaction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_discount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_ice_earning',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_partner_earning',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_platform_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_ppn',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_tax',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_user_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_voucher',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_agent',
        ),
    ]
