# Generated by Django 5.2.1 on 2025-10-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_course_price_payment_ip_address_payment_isp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='snapshot_price',
        ),
    ]
