# Generated by Django 5.2.1 on 2025-10-03 01:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_remove_payment_snapshot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='snapshot_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
