# Generated by Django 5.2.1 on 2025-10-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_snapshot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='access_granted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Payment URL'),
        ),
    ]
