# Generated by Django 5.2.1 on 2025-10-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_access_granted_payment_access_granted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
