# Generated by Django 5.2.1 on 2025-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_transaction_merchant_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='va_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
