# Generated by Django 5.2.1 on 2025-10-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_payment_bank_name_payment_va_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='va_number',
        ),
    ]
