# Generated by Django 5.2.1 on 2025-10-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_payment_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Nama Bank / Metode dari Tripay', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='instructions_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='va_number',
            field=models.CharField(blank=True, help_text='Nomor Virtual Account / Pay Code dari Tripay', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID unik dari Tripay (reference)', max_length=100, null=True, unique=True),
        ),
    ]
