# Generated by Django 5.2.1 on 2025-10-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_alter_transaction_options_transaction_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='Batas waktu pembayaran (1 jam dari created_at)', null=True),
        ),
    ]
