# Generated by Django 5.1.1 on 2025-01-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_remove_material_file'),
        ('quiz', '0005_question_section_alter_attemptedquestion_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, unique=True)),
                ('min_percentage', models.FloatField()),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.AlterField(
            model_name='score',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='GradeCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, unique=True)),
                ('min_percentage', models.FloatField()),
                ('max_percentage', models.FloatField()),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_cutoffs', to='courses.section')),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
    ]
