# Generated by Django 5.1.1 on 2025-01-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_gradingpolicy_alter_score_grade_gradecutoff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradingPolicy',
        ),
    ]
