# Generated by Django 5.1.1 on 2025-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_date_score_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedquestion',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='attempted_questions', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='user_numerical_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='user_text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('CB', 'Checkbox'), ('NI', 'Numerical Input'), ('TI', 'Text Input')], default='MC', max_length=2),
        ),
    ]
