# Generated by Django 5.1.1 on 2025-01-08 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_attemptedquestion_selected_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='selected_choices',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='user_numerical_answer',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='user_text_answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='score',
            name='edited_on',
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='GradeCutoff',
        ),
    ]
