# Generated by Django 5.1.1 on 2025-01-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_score_time_taken_alter_score_grade_alter_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
