"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*t=li&h7o=sj40!ic&)p+8!fy3p@*tfg+mz6!xuftigv_qa9yy'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
#ALLOWED_HOSTS = ['127.0.0.1','localhost']
ALLOWED_HOSTS = ['ini.icei.ac.id','20.11.247.222']
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

SECURE_SSL_REDIRECT = True
#SECURE_CONTENT_TYPE_NOSNIFF = True
RATELIMIT_IP_META_KEY = 'HTTP_X_REAL_IP'
CSRF_TRUSTED_ORIGINS = ['https://ini.icei.ac.id']
ALLOWED_REFERER = 'https://ini.icei.ac.id'




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'captcha',
    'courses',
    'instructor',
    'learner',
    'partner',
    'import_export',
    'django_ckeditor_5',
    'django_ratelimit',
    'django.contrib.sites',  # Required by django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Google provider
    'csp',
    'mathfilters',
    'blog',
    'licensing',
    'audit',#audit user
    #'payments',#semua pembayaran
    'django.contrib.humanize',
    'axes',#LOGIN LIMIT
    "django_htmx",
    'django_select2',
    'payments.apps.PaymentsConfig',  # bukan 'payments' langsung!
    'lti_consumer',  # Aplikasi LTI Consumer
    'dal',
    'dal_select2',#selct2 server
 
    
]

LTI_PLATFORM_ISS = "https://ini.icei.ac.id"

MIDDLEWARE = [
    #'django.middleware.security.SecurityMiddleware',
    'axes.middleware.AxesMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'audit.middleware.CurrentUserMiddleware',
    'audit.middleware.AuditLogMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = 'mysite.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'authentication.context_processors.search_history_context',
                'payments.context_processors.cart_item_count', 
            ],
            'libraries': {
                'learner_tags': 'learner.templatetags.learner_tags',
            },
        },
    },
]


WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',

  # Pastikan Memcached berjalan pada IP dan port ini
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'authentication.CustomUser'

LOGIN_URL = 'authentication:login'  # Ensure login page is properly redirected
LOGIN_REDIRECT_URL = 'authentication:home'  # After login, redirect to home
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
SITE_ID = 1
#SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['profile', 'email']

SOCIALACCOUNT_PROVIDERS = {
    'google':{
        'APP':{
            'client_id':'685028379285-6frcirokho5copovj8s61s33251bs8p6.apps.googleusercontent.com',
            'secret':'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',
            'key':''
        }
    }
}
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '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'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '<your-client-secret>'
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
SOCIALACCOUNT_LOGIN_ON_GET=True
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# URL untuk mengakses file statis di browser
STATIC_URL = '/static/'

# Jika Anda mengonfigurasi untuk pengumpulan file statis (collectstatic) di lingkungan produksi
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Tempat mengumpulkan file statis saat menggunakan collectstatic

# Folder tempat file statis tambahan Anda berada (selain folder static default)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Folder 'static' yang ada di dalam proyek Anda
]
# URL untuk mengakses file media (misalnya gambar, video yang di-upload pengguna)
MEDIA_URL = "/media/"

# Direktori untuk menyimpan file media yang di-upload oleh pengguna
MEDIA_ROOT = os.path.join(BASE_DIR, "media")



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pengaturan email untuk menggunakan SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Alamat email dan password aplikasi Gmail
EMAIL_HOST_USER = 'indonesialokal@gmail.com'  # Ganti dengan alamat email Anda
EMAIL_HOST_PASSWORD = 'vdee kfzo dyvk idsa'  # Ganti dengan password aplikasi Gmail Anda

# Email pengirim default untuk email otomatis
DEFAULT_FROM_EMAIL = 'Informasi dari LMSku'





customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]
CKEDITOR_5_ALLOW_ALL_FILE_TYPES = True
CKEDITOR_5_CONFIGS = {
    "default": {
        "removePlugins": ["WordCount"],
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
        "link": {
            "defaultProtocol": "https://",  # Menggunakan https:// sebagai default
            "allowedProtocols": ["https"],  # Hanya mengizinkan http:// dan https://
            "allowedDomains": [
                "youtube.com",
                "facebook.com",
                "x.com",
                "icei.ac.id",
                "tiktok.com"
            ],
            "checkCurrentDocument": False,  # Tidak memeriksa URL dokumen saat ini
        }
        
    },
   
    "comment": {
        "language": {"ui": "en", "content": "ar"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "extends": {
        "language": "en",
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": {
            "items": [
                "heading",
                "horizontalLine",
                "codeBlock",
                "htmlEmbed",
                "|",
                "outdent",
                "indent",
                "|",
                "bold",
                "italic",
                "link",
                "underline",
                "strikethrough",
                "code",
                "subscript",
                "superscript",
                "highlight",
                "|",
                "bulletedList",
                "numberedList",
                "todoList",
                "|",
                "blockQuote",
                "linkImage",
                "insertImage",
                "|",
                "fontSize",
                "fontFamily",
                "fontColor",
                "fontBackgroundColor",
                "mediaEmbed",
                "removeFormat",
                "insertTable",
                "sourceEditing",
                "style",
                "specialCharacters",
                "fileUpload",
                "showBlocks",
                "selectAll",
                "findAndReplace",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
                "toggleTableCaption",
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ],
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            },
        },
         "link": {
            "defaultProtocol": "https://",  # Menggunakan https:// sebagai default
            "allowedProtocols": ["https"],  # Hanya mengizinkan http:// dan https://
            "allowedDomains": [
                "youtube.com",
                "facebook.com",
                "x.com",
                "icei.ac.id",
                "tiktok.com"
            ],
            "checkCurrentDocument": False,  # Tidak memeriksa URL dokumen saat ini
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True},
            ],
        },
        "mention": {
            "feeds": [
                {
                    "marker": "@",
                    "feed": [
                        "@Barney",
                        "@Lily",
                        "@Marry Ann",
                        "@Marshall",
                        "@Robin",
                        "@Ted",
                    ],
                    "minimumCharacters": 1,
                },
            ],
        },
        "style": {
            "definitions": [
                {"name": "Article category", "element": "h3", "classes": ["category"]},
                {"name": "Info box", "element": "p", "classes": ["info-box"]},
            ],
        },
    },
}

CKEDITOR_5_CUSTOM_CSS = "custom.css"
CSRF_COOKIE_NAME = "new_csrf_cookie_name"
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff","is_partner","is_instructor",'authenticated'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'debug.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',  # Pastikan DEBUG aktif
            'propagate': True,
        },
    },
}



SITE_URL = 'https://ini.icei.ac.id'

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        # Hanya izinkan <base> tag mengarah ke domain sendiri
        'base-uri': ("'self'",),

        # Izinkan permintaan (AJAX, WebSocket, fetch, dsb) hanya ke domain sendiri dan ke Moodle
        'connect-src': (
            "'self'",  # domain aplikasi ini sendiri
            "https://scholldecodewp.h5p.com",  # domain Moodle untuk integrasi LTI
        ),

        # Default untuk semua jenis resource, kecuali yang punya aturan khusus di bawah
        'default-src': ("'self'",),  # semua resource hanya boleh dari domain sendiri

        # Izinkan font (woff, woff2, ttf) dari domain berikut
        'font-src': (
            "'self'",  # dari domain sendiri
            'https://cdnjs.cloudflare.com',  # CDN umum
            'https://cdn.jsdelivr.net',  # CDN umum
            'https://fonts.googleapis.com',  # stylesheet Google Fonts (kadang diminta juga)
            'https://fonts.gstatic.com',  # tempat file font Google Fonts di-host
        ),

        'frame-ancestors': (
            "'self'",  # agar bisa embed sendiri (opsional)
            'https://moodle.icei.ac.id',  # izinkan Moodle sebagai LTI consumer
            'https://asimarif.h5p.com',  # izinkan H5P sebagai LTI consumer
        ),

        # Form hanya bisa dikirim (POST) ke domain sendiri
        #'form-action': ("'self'",),

        # Izinkan iframe atau konten embedded hanya dari domain sendiri, Moodle, dan YouTube
        'frame-src': (
            "'self'",
            "https://idols.ui.ac.id",  # Moodle iframe
            "https://www.youtube-nocookie.com",
            "https://pakaimata.h5p.com",  # Izinkan YouTube iframe (tanpa cookie)
            "https://www.youtube.com",
            "https://www.youtube-nocookie.com",
            'https://scholldecodewp.h5p.com', 
            "https://moodle.icei.ac.id",  # Tambahkan ini
            "https://asimarif.h5p.com",
        ),

        # Izinkan gambar dari domain sendiri dan dari inline base64 (data:)
        'img-src': (
            "'self'",
            "data:",  # misalnya untuk gambar yang di-embed sebagai base64
        ),

        # Blokir plugin seperti Flash, Java Applet, dll — demi keamanan
        'object-src': ("'none'",),

        # Izinkan file JavaScript dari domain sendiri dan CDN berikut
        'script-src': (
            "'self'",  # dari server sendiri
            'https://cdn.jsdelivr.net',  # CDN umum
            'https://cdnjs.cloudflare.com',  # CDN umum
            "'unsafe-inline'",  # mengizinkan <script> inline — sebaiknya dihindari untuk keamanan
            "'unsafe-eval'",
            'https://scholldecodewp.h5p.com', 
        ),

        # Izinkan file CSS dari domain sendiri dan CDN berikut
        'style-src': (
            "'self'",  # dari server sendiri
            'https://cdn.jsdelivr.net',  # CDN umum
            'https://cdnjs.cloudflare.com',  # CDN umum
            'https://fonts.googleapis.com',  # stylesheet dari Google Fonts
            "'unsafe-inline'",  # mengizinkan <style> inline — sebaiknya dihindari jika memungkinkan
        ),

        # Izinkan tag <link rel="stylesheet"> yang diarahkan ke sumber eksternal tertentu (Google Fonts)
        'style-src-elem': (
            "'self'",
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://fonts.googleapis.com',
            "'unsafe-inline'",
        ),
        'form-action': (
            "'self'",
            "https://vclass.unila.ac.id",  # domain Moodle tujuan POST LTI
            "https://idols.ui.ac.id",
            "https://scholldecodewp.h5p.com",
            "https://moodle.icei.ac.id",
            "https://asimarif.h5p.com",  # domain H5P untuk LTI
          
        ),
    }
}


# settings.py
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]
# settings.py

# settings.py

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 jam
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # ganti yang deprecated

LTI_ISSUER = "https://ini.icei.ac.id"  # domain lms to lti
LTI_CLIENT_ID = "https://scholldecodewp.h5p.com"  # Sesuaikan dengan data dari H5P


CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_MATH_CHALLENGE_QUESTION = 'What is {num1} plus {num2}?'



