# Generated by Django 3.2.12 on 2022-09-27 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
