# Generated by Django 3.2.12 on 2022-09-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220927_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
