# Generated by Django 5.1.7 on 2025-05-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='subscription_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('once', 'One-time')], default='monthly', max_length=20, verbose_name='Subscription Frequency'),
        ),
        migrations.AddField(
            model_name='license',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('trial', 'Trial')], default='paid', max_length=20, verbose_name='Subscription Type'),
        ),
    ]
