# Generated by Django 5.1.7 on 2025-05-05 02:15

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_subscription_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='Invitee Email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='Status')),
                ('invitation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invitation Date')),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2025, 5, 12, 2, 15, 5, 923343, tzinfo=datetime.timezone.utc), verbose_name='Expiry Date')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Inviter')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.license', verbose_name='Assigned License')),
            ],
        ),
    ]
