# Generated by Django 5.1.7 on 2025-05-05 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 2, 58, 37, 185872, tzinfo=datetime.timezone.utc), verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Invitation Date'),
        ),
    ]
