# Generated by Django 5.1.7 on 2025-05-05 06:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_invitation_token_alter_invitation_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.AddField(
            model_name='license',
            name='users',
            field=models.ManyToManyField(related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 6, 54, 53, 818584, tzinfo=datetime.timezone.utc), verbose_name='Expiry Date'),
        ),
    ]
