# Generated by Django 5.1.7 on 2025-05-05 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_remove_license_user_license_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='max_users',
            field=models.PositiveIntegerField(default=20, verbose_name='Maximum Users'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 6, 58, 24, 658533, tzinfo=datetime.timezone.utc), verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='subscription_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('once', 'One-time')], default='yearly', max_length=20, verbose_name='Subscription Frequency'),
        ),
    ]
