# Generated by Django 5.1.7 on 2025-05-05 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_license_max_users_alter_invitation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 6, 59, 22, 27306, tzinfo=datetime.timezone.utc), verbose_name='Expiry Date'),
        ),
    ]
