# Generated by Django 5.1.7 on 2025-05-05 08:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_universiti_kode'),
        ('courses', '0016_lastaccesscourse'),
        ('licensing', '0007_alter_invitation_expiry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Lisensi', 'verbose_name_plural': 'Lisensi'},
        ),
        migrations.AddField(
            model_name='license',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='courses.course', verbose_name='Kursus'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 8, 0, 3, 331140, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Undangan'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitee_email',
            field=models.EmailField(max_length=254, verbose_name='Email Penerima'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Pengundang'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.license', verbose_name='Lisensi Terkait'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('accepted', 'Diterima'), ('expired', 'Kadaluarsa')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(verbose_name='Tanggal Berakhir'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('free', 'Gratis'), ('paid', 'Berbayar'), ('trial', 'Uji Coba')], default='trial', max_length=10, verbose_name='Tipe Lisensi'),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_users',
            field=models.PositiveIntegerField(default=20, verbose_name='Maksimum Pengguna'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Lisensi'),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='license',
            name='subscription_frequency',
            field=models.CharField(choices=[('monthly', 'Bulanan'), ('yearly', 'Tahunan'), ('once', 'Sekali')], default='yearly', max_length=20, verbose_name='Frekuensi Langganan'),
        ),
        migrations.AlterField(
            model_name='license',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Gratis'), ('paid', 'Berbayar'), ('trial', 'Uji Coba')], default='paid', max_length=20, verbose_name='Tipe Langganan'),
        ),
        migrations.AlterField(
            model_name='license',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.universiti', verbose_name='Universitas'),
        ),
        migrations.AlterField(
            model_name='license',
            name='users',
            field=models.ManyToManyField(related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
    ]
