# Generated by Django 5.1.7 on 2025-05-05 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_alter_license_options_license_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='courses',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 8, 8, 4, 117006, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
