# Generated by Django 5.2.1 on 2025-06-16 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0047_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 5, 0, 17, 461941, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
