# Generated by Django 5.2.1 on 2025-06-30 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0075_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 1, 52, 36, 882522, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
