# Generated by Django 5.2.1 on 2025-10-01 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0096_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 4, 34, 3, 817309, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
