# Generated by Django 5.2.1 on 2025-10-22 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0131_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 9, 25, 26, 674943, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
