# Generated by Django 5.2.1 on 2025-11-03 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0140_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 3, 4, 28, 841256, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
