# Generated by Django 5.1.1 on 2024-10-15 04:11

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('topic', models.CharField(max_length=250)),
                ('course_overview', models.TextField(null=True)),
                ('category', models.CharField(choices=[('tecnologi', 'tecnologi'), ('law', 'law'), ('economic', 'economic'), ('social', 'social'), ('agriculture', 'agriculture'), ('mining', 'mining'), ('management', 'management'), ('program', 'program')], max_length=50, null=True)),
                ('number_of_questions', models.IntegerField(null=True)),
                ('time', models.IntegerField(help_text='durations of the quiz in minutes', null=True)),
                ('required_score_to_pas', models.IntegerField(null=True, verbose_name='required score in %')),
                ('level', models.CharField(choices=[('basic', 'basic'), ('medium', 'medium'), ('advanced', 'advanced')], default='basic', max_length=10, null=True)),
                ('status_course', models.CharField(choices=[('draft', 'draft'), ('qurations', 'qurations'), ('publish', 'publish'), ('pending', 'pending')], default='draft', max_length=10)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_enrol', models.DateField(null=True)),
                ('end_enrol', models.DateField(null=True)),
                ('effort', models.CharField(max_length=20, null=True)),
                ('lang', models.CharField(choices=[('en', 'english'), ('id', 'indonesia')], default='id', max_length=30)),
                ('type_course', models.CharField(choices=[('self', 'self-paced'), ('instructor', 'instructor-paced')], default='self', max_length=10)),
                ('image_course', models.ImageField(null=True, upload_to=courses.models.filepath)),
                ('course_year', models.IntegerField(default=courses.models.current_year, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
    ]
