# Generated by Django 5.1.7 on 2025-04-16 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='auth_login_url',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='auth_token_url',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='deployment_id',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='key_set_url',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='ltiplatformconfiguration',
            name='public_key',
        ),
        migrations.AddField(
            model_name='ltiplatformconfiguration',
            name='consumer_key',
            field=models.CharField(default=django.utils.timezone.now, help_text='Consumer key dari Tool Provider', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltiplatformconfiguration',
            name='platform_name',
            field=models.CharField(blank=True, help_text='Nama platform, misalnya Moodle', max_length=255),
        ),
        migrations.AddField(
            model_name='ltiplatformconfiguration',
            name='shared_secret',
            field=models.CharField(default=django.utils.timezone.now, help_text='Shared secret untuk autentikasi LTI', max_length=255),
            preserve_default=False,
        ),
    ]
