# Generated by Django 5.1.1 on 2025-02-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askora',
            name='file_requirement',
        ),
    ]
