# Generated by Django 5.1.1 on 2025-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_score_assessment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='assessment_score',
        ),
    ]
