# Generated by Django 5.1.7 on 2025-04-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_ltiplatformconfiguration_auth_login_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='max_grade',
        ),
    ]
