# Generated by Django 5.1.1 on 2025-01-26 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_universiti_user_university'),
        ('courses', '0002_alter_universiti_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_univ', to='auth.universiti'),
        ),
        migrations.DeleteModel(
            name='Universiti',
        ),
    ]
