# Generated by Django 5.1.1 on 2024-10-22 05:29

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='effort',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_enrol',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.filepath),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_score_to_pas',
            field=models.IntegerField(blank=True, null=True, verbose_name='required score in %'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_enrol',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(blank=True, help_text='durations of the quiz in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
