# Generated by Django 5.1.1 on 2025-02-25 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_askora_file_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='askora',
            name='response_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
