# Generated by Django 5.1.7 on 2025-03-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_sospost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
