# Generated by Django 5.1.7 on 2025-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_ltiexternaltool_max_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiexternaltool',
            name='cartridge_url',
            field=models.URLField(blank=True, help_text='URL cartridge untuk konfigurasi LTI'),
        ),
    ]
