# Generated by Django 5.1.1 on 2024-11-15 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_courses', to='courses.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='org_partner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_courses', to='courses.partner'),
            preserve_default=False,
        ),
    ]
