# Generated by Django 5.1.1 on 2025-02-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_askora_response_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
