# Generated by Django 5.1.1 on 2025-02-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_score_assessment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcredential',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microcredentials', to='courses.category'),
        ),
        migrations.AddField(
            model_name='microcredential',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microcredential',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='microcredentials/'),
        ),
        migrations.AddField(
            model_name='microcredential',
            name='min_total_score',
            field=models.FloatField(default=0.0, help_text='Total minimum score required across all courses'),
        ),
        migrations.AddField(
            model_name='microcredential',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microcredential',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
