# Generated by Django 5.1.7 on 2025-03-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sospost',
            name='content',
            field=models.TextField(max_length=150),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='courses.sospost')),
            ],
        ),
    ]
