# Generated by Django 5.1.7 on 2025-04-21 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_ltiexternaltool_cartridge_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='cartridge_url',
        ),
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='has_grade',
        ),
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='platform_config',
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='consumer_key',
            field=models.CharField(blank=True, help_text='Consumer key dari Moodle (boleh dikosongkan jika Moodle tidak memerlukannya)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='shared_secret',
            field=models.CharField(default=django.utils.timezone.now, help_text='Shared secret dari Moodle, digunakan untuk OAuth 1.0 signing', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='launch_url',
            field=models.URLField(help_text='Launch URL dari Moodle, contoh: https://idols.ui.ac.id/enrol/lti/tool.php?id=5'),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='name',
            field=models.CharField(help_text="Nama tool (misalnya: 'Moodle Kelas 1')", max_length=255),
        ),
    ]
