# Generated by Django 5.1.1 on 2025-02-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_peerreview_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='askora',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
