# Generated by Django 5.1.1 on 2025-02-04 02:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_partner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name.slug', unique=True),
        ),
    ]
