# Generated by Django 5.1.1 on 2024-11-15 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_partner_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='abbreviation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='account_holder_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='account_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tax',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
