# Generated by Django 5.1.1 on 2024-10-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_enrol',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='course',
            name='required_score_to_pas',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_enrol',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type_course',
        ),
    ]
