# Generated by Django 5.1.7 on 2025-04-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_ltiexternaltool_cartridge_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LTIPlatformConfiguration',
        ),
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='launch_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='shared_secret',
            field=models.CharField(max_length=255),
        ),
    ]
