# Generated by Django 5.1.1 on 2025-02-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_partner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
