# Generated by Django 5.1.7 on 2025-03-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sospost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='sospost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='sospost',
            name='retweet',
        ),
        migrations.AlterField(
            model_name='sospost',
            name='content',
            field=models.TextField(),
        ),
    ]
