# Generated by Django 5.1.7 on 2025-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_ltiplatformconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiexternaltool',
            name='lti_passport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
