# Generated by Django 5.1.1 on 2024-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_partner_abbreviation_partner_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='join',
        ),
        migrations.AlterField(
            model_name='partner',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
