# Generated by Django 5.1.1 on 2025-02-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_partner_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='slug',
        ),
    ]
