# Generated by Django 5.1.7 on 2025-04-25 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_ltiexternaltool_lti_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursecomment'),
        ),
    ]
