# Generated by Django 5.1.7 on 2025-03-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_sospost_dislikes_remove_sospost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sospost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.sospost'),
        ),
    ]
