# Generated by Django 5.1.1 on 2024-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_partner_join_alter_partner_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
