# Generated by Django 5.1.1 on 2024-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='org_partner',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'technology'), ('law', 'law'), ('economic', 'economic'), ('social', 'social'), ('agriculture', 'agriculture'), ('mining', 'mining'), ('management', 'management'), ('program', 'program')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_run',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('basic', 'basic'), ('medium', 'medium'), ('advanced', 'advanced')], default='basic', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='status_course',
            field=models.CharField(blank=True, choices=[('draft', 'draft'), ('qurations', 'qurations'), ('publish', 'publish'), ('pending', 'pending')], default='draft', max_length=10),
        ),
    ]
