# Generated by Django 5.1.1 on 2025-02-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_pricingtype_courseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprice',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
