# Generated by Django 5.1.7 on 2025-03-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='partner',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tiktok'),
        ),
        migrations.AddField(
            model_name='partner',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='partner',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='youtube'),
        ),
    ]
