# Generated by Django 5.1.1 on 2025-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseprice_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateAdminPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Pricing Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (IDR)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
