# Generated by Django 5.1.1 on 2024-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='mySection',
        ),
    ]
