# Generated by Django 5.1.1 on 2024-10-22 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_org_partner_alter_course_category_and_more'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='org_partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
            preserve_default=False,
        ),
    ]
