# Generated by Django 5.1.1 on 2024-11-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_section_mysection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mySection',
            new_name='Section',
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'section'},
        ),
    ]
