# Generated by Django 5.1.7 on 2025-03-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_partner_facebook_partner_instagram_partner_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
