# Generated by Django 5.1.1 on 2025-02-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_calculateadminprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='iceiprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='share icei (IDR)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax (IDR)'),
        ),
    ]
