# Generated by Django 5.1.1 on 2025-02-06 06:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_partner_iceiprice_alter_partner_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprice',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='start_date',
        ),
        migrations.AddField(
            model_name='courseprice',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Admin Fee'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='admin_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='ICE Share (%)'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='calculate_admin_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_prices', to='courses.calculateadminprice'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='ice_earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ICE Earning'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='iceiprice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ICE Share (IDR)'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Normal Price'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_prices', to='courses.partner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprice',
            name='partner_earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Partner Earning'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='partner_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Partner Price'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10, verbose_name='Platform Fee'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='portal_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Portal Price'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='PPN'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='ppn_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), max_digits=5, verbose_name='PPN (%)'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sub Total'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax (IDR)'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='user_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='User Payment'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='voucher',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Voucher'),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
