# Generated by Django 5.1.1 on 2025-02-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_courseprice_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprice',
            name='amount',
        ),
    ]
