# Generated by Django 5.1.7 on 2025-04-30 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_microcredentialcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('microcredential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.microcredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
