# Generated by Django 5.1.7 on 2025-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
    ]
