# Generated by Django 5.1.1 on 2024-12-13 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_edited_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['user'], name='courses_par_user_id_86e67c_idx'),
        ),
    ]
