# Generated by Django 5.1.1 on 2025-02-06 07:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_courseprice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprice',
            name='iceiprice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ICE Share (%)'),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax (%)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='iceiprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='share icei (%)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax (%)'),
        ),
    ]
