# Generated by Django 5.1.7 on 2025-04-30 07:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_microclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='microclaim',
            name='certificate_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
