# Generated by Django 5.1.7 on 2025-04-30 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_microclaim_certificate_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='microclaim',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
