# Generated by Django 5.1.1 on 2025-02-06 07:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_courseprice_iceiprice_alter_courseprice_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprice',
            name='partner_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Partner Price'),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Platform Fee'),
        ),
    ]
