# Generated by Django 5.1.1 on 2024-12-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_description_course_end_date_course_end_enrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status_course',
            field=models.CharField(blank=True, choices=[('draft', 'draft'), ('published', 'published'), ('curation', 'curation'), ('archive', 'archive')], default='draft', max_length=10),
        ),
    ]
