# Generated by Django 5.1.7 on 2025-05-14 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lastaccesscourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='lti_passport',
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='custom_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assessment'),
        ),
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='consumer_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
