# Generated by Django 5.1.1 on 2024-10-24 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_org_partner_instructor_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='mycourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
