# Generated by Django 5.1.1 on 2024-10-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_instructor_mycourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, choices=[('draft', 'draft'), ('qurations', 'qurations'), ('publish', 'publish'), ('pending', 'pending')], default='draft', max_length=200)),
                ('category_slug', models.CharField(blank=True, choices=[('draft', 'draft'), ('qurations', 'qurations'), ('publish', 'publish'), ('pending', 'pending')], default='draft', max_length=200)),
            ],
        ),
    ]
