# Generated by Django 5.1.1 on 2024-12-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
