# Generated by Django 5.1.7 on 2025-05-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_ltiexternaltool_lti_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiexternaltool',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_tools', to='courses.assessment'),
        ),
    ]
