# Generated by Django 5.2.1 on 2025-05-19 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_ltiexternaltool_assessment'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_model',
            field=models.CharField(choices=[('buy_first', 'Beli dulu baru enrol'), ('pay_for_exam', 'Enrol dulu, bayar saat ujian'), ('pay_for_certificate', 'Enrol & ujian dulu, bayar saat sertifikat'), ('free', 'Gratis')], default='buy_first', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='payments.payment'),
        ),
    ]
