# Generated by Django 5.2.1 on 2025-05-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_payment_model_course_price_enrollment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
