# Generated by Django 5.1.1 on 2024-12-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='university',
        ),
    ]
