# Generated by Django 5.2.1 on 2025-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_model',
            field=models.CharField(choices=[('buy first', 'Buy first, then enroll'), ('pay for exam', 'Enroll first, pay at exam'), ('pay for certificate', 'Enroll & take exam first, pay at certificate claim'), ('free', 'Free')], default='buy first', max_length=20),
        ),
    ]
