# Generated by Django 5.1.1 on 2025-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_assessmentread_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='progress_percentage',
            field=models.FloatField(default=0),
        ),
    ]
