# Generated by Django 5.2.1 on 2025-05-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[], default='id', max_length=2),
        ),
    ]
