# Generated by Django 5.1.1 on 2025-02-14 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_courseprogress_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='choice',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='courses.choice'),
            preserve_default=False,
        ),
    ]
