# Generated by Django 5.1.1 on 2025-02-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_questionanswer_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.graderange'),
        ),
    ]
