# Generated by Django 5.2.1 on 2025-05-20 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status_course', 'end_enrol'], name='courses_cou_status__7f06f5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'language', 'level'], name='courses_cou_categor_77641f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['org_partner'], name='courses_cou_org_par_27dad4_idx'),
        ),
    ]
