# Generated by Django 5.1.1 on 2024-12-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_partner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='abbreviation',
        ),
    ]
