# Generated by Django 5.1.1 on 2025-02-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseprogress_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration_in_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
