# Generated by Django 5.2.1 on 2025-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_courses_cou_status__7f06f5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
