# Generated by Django 5.2.1 on 2025-06-13 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'date')},
            },
        ),
    ]
