# Generated by Django 5.1.1 on 2025-02-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_assessment_duration_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
