# Generated by Django 5.1.1 on 2024-12-31 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_partner_name_alter_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to='courses.instructor'),
            preserve_default=False,
        ),
    ]
