# Generated by Django 5.1.1 on 2024-11-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_course_org_partner'),
        ('partner', '0004_alter_partner_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='org_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
