# Generated by Django 5.1.1 on 2024-12-31 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_instructor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.partner'),
        ),
    ]
