# Generated by Django 5.2.1 on 2025-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_coursesessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionlog',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursesessionlog',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
