# Generated by Django 5.1.1 on 2024-12-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_instructor_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
