# Generated by Django 5.2.1 on 2025-06-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='tech',
            field=models.TextField(),
        ),
    ]
