# Generated by Django 5.2.1 on 2025-06-26 09:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_instructor_tech'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default LMS Key', max_length=255)),
                ('private_key', models.TextField(blank=True, help_text='RSA private key in PEM format')),
                ('public_jwk', models.JSONField(blank=True, help_text='Public JWK for LTI 1.3', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_key', to='courses.partner')),
            ],
            options={
                'verbose_name': 'Platform RSA Key',
                'verbose_name_plural': 'Platform RSA Keys',
            },
        ),
    ]
