# Generated by Django 5.2.1 on 2025-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_platformkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformkey',
            options={'permissions': [('can_generate_rsa_key', 'Can generate RSA Key Pair for LTI 1.3')], 'verbose_name': 'Platform RSA Key', 'verbose_name_plural': 'Platform RSA Keys'},
        ),
    ]
