# Generated by Django 5.2.1 on 2025-06-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_platformkey_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformkey',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.partner'),
        ),
    ]
