# Generated by Django 5.1.1 on 2025-01-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
    ]
