# Generated by Django 5.2.1 on 2025-06-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_platformkey_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.URLField()),
                ('client_id', models.CharField(max_length=512)),
                ('login_url', models.URLField()),
                ('launch_url', models.URLField()),
                ('jwks_url', models.URLField()),
                ('audience', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
