# Generated by Django 5.2.1 on 2025-06-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_ltiplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiplatform',
            name='audience',
            field=models.CharField(blank=True, help_text="(Opsional) Nilai 'aud' dalam id_token. Jika kosong, akan dianggap sama dengan client_id.", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='client_id',
            field=models.CharField(help_text='Client ID yang diberikan oleh Tool Provider. Biasanya sama dengan issuer, tapi bisa berbeda.', max_length=512),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Waktu entri ini dibuat. Diisi otomatis oleh sistem.'),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='issuer',
            field=models.URLField(help_text="URL unik dari Tool Provider sebagai 'iss' dalam id_token JWT. Contoh: https://asimarif.h5p.com"),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='jwks_url',
            field=models.URLField(help_text='URL public JWKS milik Tool Provider. LMS akan mengambil public key dari sini untuk verifikasi JWT.'),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='launch_url',
            field=models.URLField(help_text='URL tujuan LTI launch di sisi Tool. Biasanya ditentukan oleh Tool, bisa digunakan untuk referensi.'),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='login_url',
            field=models.URLField(help_text='URL login initiation dari Tool. LMS akan redirect ke sini saat memulai login LTI.'),
        ),
        migrations.AlterField(
            model_name='ltiplatform',
            name='name',
            field=models.CharField(help_text='Nama identitas dari Tool Provider, misalnya: H5P, Labster, Moodle, dsb.', max_length=255),
        ),
    ]
