# Generated by Django 5.1.1 on 2025-01-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
    ]
