# Generated by Django 5.2.1 on 2025-06-30 03:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_ltiplatform_audience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='consumer_key',
        ),
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='launch_url',
        ),
        migrations.RemoveField(
            model_name='ltiexternaltool',
            name='shared_secret',
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='deep_link_return_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='courses.ltiplatform'),
            preserve_default=False,
        ),
    ]
