# Generated by Django 5.2.1 on 2025-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_remove_ltiexternaltool_consumer_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='expertise',
            field=models.TextField(),
        ),
    ]
