# Generated by Django 5.2.1 on 2025-07-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_instructor_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiplatform',
            name='auth_login_url',
            field=models.URLField(default='https://moodle.icei.ac.id/mod/lti/auth.php'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltiplatform',
            name='auth_token_url',
            field=models.URLField(default='https://moodle.icei.ac.id/mod/lti/certs.php'),
            preserve_default=False,
        ),
    ]
