# Generated by Django 5.2.1 on 2025-07-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_ltiplatform_auth_login_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIExternalTool1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('launch_url', models.URLField(help_text='LTI launch URL dari provider.')),
                ('consumer_key', models.CharField(help_text='Consumer key (diberikan oleh provider).', max_length=255)),
                ('shared_secret', models.CharField(help_text='Shared secret (diberikan oleh provider atau dibuat otomatis).', max_length=255)),
                ('custom_parameters', models.TextField(blank=True, help_text='Custom parameters (format: key=value, satu per baris).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lti_tool', to='courses.assessment')),
            ],
        ),
    ]
