# Generated by Django 5.2.1 on 2025-07-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_ltiexternaltool1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformkey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='platformkey',
            name='partner',
        ),
        migrations.DeleteModel(
            name='LTIExternalTool',
        ),
        migrations.DeleteModel(
            name='LTIPlatform',
        ),
        migrations.DeleteModel(
            name='PlatformKey',
        ),
    ]
