# Generated by Django 5.2.1 on 2025-07-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_remove_platformkey_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiexternaltool1',
            name='tool_url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
