# Generated by Django 5.1.1 on 2025-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_remove_course_assignment_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttype',
            name='course',
        ),
        migrations.RemoveField(
            model_name='graderange',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='assignment_types',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.assignmenttype'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_ranges',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.graderange'),
        ),
    ]
