# Generated by Django 5.2.1 on 2025-08-08 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_instructorcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='business_type',
            field=models.CharField(blank=True, choices=[('perorangan', 'Perorangan'), ('cv', 'CV'), ('pt', 'PT'), ('institusi', 'Institusi Pendidikan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='currency',
            field=models.CharField(default='IDR', max_length=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='finance_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_pkp',
            field=models.BooleanField(default=False, verbose_name='PKP (Pengusaha Kena Pajak)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='npwp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='npwp_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/npwp/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('ewallet', 'E-Wallet')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
