# Generated by Django 5.1.1 on 2025-01-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_remove_course_assignment_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment_types',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.assignmenttype'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_ranges',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.graderange'),
        ),
        migrations.AddField(
            model_name='course',
            name='grading_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courses.gradingpolicy'),
        ),
    ]
