# Generated by Django 5.2.1 on 2025-08-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_partner_business_type_partner_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastaccesscourse',
            options={'verbose_name': 'Last Access Course', 'verbose_name_plural': 'Last Access Courses'},
        ),
    ]
