# Generated by Django 5.1.1 on 2025-01-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_course_assignment_types_course_grade_ranges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignment_types',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='grade_ranges',
        ),
        migrations.RemoveField(
            model_name='course',
            name='grading_policy',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssignmentType',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradeRange',
        ),
        migrations.DeleteModel(
            name='GradingPolicy',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
