# Generated by Django 5.2.1 on 2025-09-22 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_alter_lastaccesscourse_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verifiable_credential',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='coursesessionlog',
            index=models.Index(fields=['user', 'course', 'ended_at'], name='courses_cou_user_id_66e6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesessionlog',
            index=models.Index(fields=['started_at'], name='courses_cou_started_beef10_idx'),
        ),
    ]
