# Generated by Django 5.2.1 on 2025-10-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_certificate_verifiable_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_model',
            field=models.CharField(max_length=20),
        ),
    ]
