# Generated by Django 5.1.1 on 2025-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_question_choice_attemptedquestion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
