# Generated by Django 5.2.1 on 2025-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_course_payment_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingtype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pricingtype',
            name='code',
            field=models.SlugField(help_text="Kode unik sistem. Contoh: 'free', 'buy_first', 'subscription'", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricingtype',
            name='name',
            field=models.CharField(help_text="Nama tampilan. Contoh: 'Free', 'Buy First'", max_length=50, unique=True),
        ),
    ]
