# Generated by Django 5.1.1 on 2025-01-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_alter_choice_text_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
