# Generated by Django 5.2.1 on 2025-10-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_alter_pricingtype_options_pricingtype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
