# Generated by Django 5.1.1 on 2025-01-16 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_assessment_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course'),
        ),
    ]
