# Generated by Django 5.2.1 on 2025-10-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_alter_course_payment_model'),
    ]

    operations = [
    ]
