# Generated by Django 5.2.1 on 2025-10-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_auto_20251001_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_with_payment_model', to='courses.pricingtype'),
        ),
    ]
