# Generated by Django 5.1.1 on 2025-01-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_alter_section_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.section'),
        ),
    ]
