# Generated by Django 5.2.1 on 2025-10-02 04:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_alter_course_payment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprice',
            name='calculate_admin_price',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='ice_earning',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='ice_share_rate',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='ice_share_value',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='partner_earning',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='ppn_rate',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='user_payment',
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='voucher',
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='partner_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='portal_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
