# Generated by Django 5.1.1 on 2025-01-16 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_graderange_assessment_grade_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderange',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_ranges', to='courses.course'),
            preserve_default=False,
        ),
    ]
