# Generated by Django 5.2.1 on 2025-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_remove_courseprice_calculate_admin_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseprice',
            constraint=models.UniqueConstraint(fields=('course', 'price_type', 'partner'), name='unique_course_price'),
        ),
    ]
