# Generated by Django 5.1.1 on 2025-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_graderange_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
