# Generated by Django 5.2.1 on 2025-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_remove_courseprice_unique_course_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseprice',
            name='unique_course_price',
        ),
        migrations.AddConstraint(
            model_name='courseprice',
            constraint=models.UniqueConstraint(fields=('course', 'price_type', 'partner'), name='unique_course_price'),
        ),
    ]
