# Generated by Django 5.1.1 on 2025-01-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_alter_partner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
