# Generated by Django 5.2.1 on 2025-10-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_remove_courseprice_unique_course_price_and_more'),
    ]

    operations = [
    ]
