# Generated by Django 5.2.1 on 2025-10-14 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20251003_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprice',
            name='ice_share_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
