# Generated by Django 5.2.1 on 2025-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_courseprice_ice_share_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
