# Generated by Django 5.2.1 on 2025-10-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_useractivitylog_ip_address_useractivitylog_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, help_text='User must check this box to indicate agreement.', verbose_name='Agree to Contract Terms and Applicable Rules'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('cv', 'Limited Partnership (CV)'), ('pt', 'Limited Liability Company (PT)'), ('institution', 'Educational Institution')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_pkp',
            field=models.BooleanField(default=False, verbose_name='Taxable Entrepreneur (PKP)'),
        ),
    ]
