# Generated by Django 5.2.1 on 2025-10-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_partner_agreed_to_terms_alter_partner_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('revision', 'Revision Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current review status of the partner request.', max_length=20),
        ),
    ]
