# Generated by Django 5.2.1 on 2025-10-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_partner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin notes for revision or rejection.', null=True),
        ),
    ]
