# Generated by Django 5.2.1 on 2025-11-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_partner_admin_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingtype',
            options={'ordering': ['name'], 'verbose_name': 'Pricing Type', 'verbose_name_plural': 'Pricing Types'},
        ),
        migrations.AlterField(
            model_name='pricingtype',
            name='code',
            field=models.SlugField(blank=True, help_text="Kode unik sistem. Contoh: 'free', 'buy_first', 'subscription'", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricingtype',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi singkat tentang jenis harga (opsional).', null=True),
        ),
    ]
