# Generated by Django 5.1.7 on 2025-03-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_audit',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin audit.', verbose_name='audit status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin instructor.', verbose_name='instructor status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_learner',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin learner.', verbose_name='learner status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin member.', verbose_name='member status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_note',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin note.', verbose_name='note status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin partner.', verbose_name='partner status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscription',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin subscription.', verbose_name='subscription status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, verbose_name='tiktok'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='youtube'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
