# Generated by Django 5.1.7 on 2025-03-07 08:32

import authentication.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_facebook_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Secondary', 'Secondary'), ('Higher', 'Higher'), ('Diploma', 'Diploma'), ("Bachelor's", 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=10, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobby',
            field=models.CharField(blank=True, max_length=150, verbose_name='hobby'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default=django.utils.timezone.now, max_length=8, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=authentication.models.CustomUser)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='authentication.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
