# Generated by Django 5.1.7 on 2025-04-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='universiti',
            name='kode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
