# Generated by Django 5.2.1 on 2025-09-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0005_universiti_kode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='authenticat_email_486e08_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_learner'], name='authenticat_is_lear_db4853_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_partner'], name='authenticat_is_part_ea2616_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['university'], name='authenticat_univers_25dbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['gender'], name='authenticat_gender_799d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='authenticat_date_jo_e2032e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_0cde8a_idx'),
        ),
    ]
