# Generated by Django 5.2.1 on 2025-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_curation',
            field=models.BooleanField(blank=True, default=False, help_text='Designates whether the user can log into this admin curation.', null=True, verbose_name='curation status'),
        ),
    ]
