# Generated by Django 5.2.1 on 2025-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_is_curation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_curation',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin note.', null=True, verbose_name='note status'),
        ),
    ]
