# Generated by Django 5.2.1 on 2025-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_is_curation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_finance',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin finance.', verbose_name='finance status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_marketing',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin marketing.', verbose_name='marketing status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_support',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin support.', verbose_name='support status'),
        ),
    ]
