# Generated by Django 5.2.7 on 2025-10-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_is_finance_customuser_is_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('secondary', 'Secondary'), ('higher', 'Higher'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's"), ('master', 'Master'), ('doctorate', 'Doctorate')], max_length=20, null=True, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='gender'),
        ),
    ]
