# Generated by Django 5.2.1 on 2025-08-14 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTIExternalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('deployment_id', models.CharField(max_length=255)),
                ('auth_login_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('auth_token_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('jwks_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('issuer', models.CharField(help_text="The Tool's iss in id_token", max_length=1024)),
                ('deep_linking_supported', models.BooleanField(default=False)),
                ('scopes', models.TextField(blank=True, help_text='Space/newline separated scopes, e.g. https://purl.imsglobal.org/spec/lti-ags/scope/score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=128, unique=True)),
                ('alg', models.CharField(default='RS256', max_length=10)),
                ('private_key_pem', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LTILink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_link_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_link_uri', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('custom_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='lti_consumer.ltiexternaltool')),
            ],
        ),
        migrations.CreateModel(
            name='LTILaunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_hint', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti_consumer.ltiexternaltool')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti_consumer.ltilink')),
            ],
        ),
        migrations.AddField(
            model_name='ltiexternaltool',
            name='platform_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='lti_consumer.platformkey'),
        ),
    ]
