# Generated by Django 5.2.1 on 2025-08-15 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_partner_business_type_partner_currency_and_more'),
        ('lti_consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltilink',
            name='assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lti13_link', to='courses.assessment'),
        ),
    ]
