# Generated by Django 5.2.1 on 2025-05-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_auditlog_device_info_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
