# Generated by Django 5.2.1 on 2025-05-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditlog_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
