# forms.py
import requests
import xml.etree.ElementTree as ET
import re
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django import forms
from django.forms import inlineformset_factory
from django.core.cache import cache
from .models import MicroCredentialComment,LTIExternalTool1,MicroCredentialReview,Course,SosPost,CourseStatus,CourseRating,MicroCredential, AskOra,Partner,Category, Section,Instructor,TeamMember,GradeRange, Material,Question, Choice,Assessment,PricingType, CoursePrice
from django_ckeditor_5.widgets import CKEditor5Widget
import os
from authentication.models import CustomUser, Universiti
import logging
from django.utils.text import slugify
from django.core.files.base import ContentFile
from PIL import Image as PILImage
import io
from datetime import date
from django.core.exceptions import ValidationError
from django.utils import timezone
from captcha.fields import CaptchaField
import xml.etree.ElementTree as ET
import hashlib
from django_select2.forms import ModelSelect2MultipleWidget
from dal import autocomplete
from decimal import Decimal

logger = logging.getLogger(__name__)





class MicroCredentialCommentForm(forms.ModelForm):
    class Meta:
        model = MicroCredentialComment
        fields = ['content']  # Form hanya meminta konten komentar

    def __init__(self, *args, **kwargs):
        super(MicroCredentialCommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Write your comment here...'})

class MicroCredentialReviewForm(forms.ModelForm):
    class Meta:
        model = MicroCredentialReview
        fields = ['rating', 'review_text']
        widgets = {
            'review_text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write your review here...'}),
        }
        
class LTIExternalToolForm(forms.ModelForm):
    class Meta:
        model = LTIExternalTool1
        fields = [
            'tool_name',
            'launch_url',
            'tool_url',
            'consumer_key',
            'shared_secret',
            'custom_parameters',
        ]
        labels = {
            'tool_name': 'Tool Name',
            'launch_url': 'Launch URL',
            'tool_url': 'Tool URL (optional)',
            'consumer_key': 'Consumer Key',
            'shared_secret': 'Shared Secret',
            'custom_parameters': 'Custom Parameters',
        }
        help_texts = {
            'launch_url': 'LTI launch URL provided by the external tool.',
            'tool_url': 'Optional homepage or tool info URL.',
            'consumer_key': 'Provided by the LTI platform.',
            'shared_secret': 'Provided or generated by the LTI platform.',
            'custom_parameters': 'Optional: One key=value per line.',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        
        self.fields['tool_name'].widget.attrs.update({
            'placeholder': 'e.g., H5P, Labster, Moodle Quiz Tool'
        })
        self.fields['launch_url'].widget.attrs.update({
            'placeholder': 'https://provider.com/lti/launch'
        })
        self.fields['tool_url'].widget.attrs.update({
            'placeholder': 'https://provider.com'
        })
        self.fields['consumer_key'].widget.attrs.update({
            'placeholder': 'Enter the consumer key provided by the tool'
        })
        self.fields['shared_secret'].widget.attrs.update({
            'placeholder': 'Enter the shared secret'
        })
        self.fields['custom_parameters'].widget.attrs.update({
            'placeholder': 'key1=value1\nkey2=value2\n(optional)',
            'rows': 4,
        })


class CourseRatingForm(forms.ModelForm):
    class Meta:
        model = CourseRating
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.Select(attrs={'class': 'form-select'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

class SosPostForm(forms.ModelForm):
    #captcha = CaptchaField()
    
    class Meta:
        model = SosPost
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'rows': 2,
                'maxlength': 150,
                'class': 'form-control',
                'placeholder': 'Apa yang ada di pikiranmu?',
                'hx-target': '#post-list',
                'hx-swap': 'prepend'
            }),
        }

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) > 150:
            raise forms.ValidationError("Maksimum 150 karakter!")
        return content

class MicroCredentialForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditor5Widget())

    class Meta:
        model = MicroCredential
        fields = ['title', 'slug', 'description', 'required_courses', 'status', 'start_date', 'end_date', 'image', 'category', 'min_total_score']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 100%; font-size: 18px;', "oninput": "listingslug(value)"}),
            'slug': forms.HiddenInput(attrs={"class": "form-control", "maxlength": "200"}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'required_courses': autocomplete.ModelSelect2Multiple(
                url='courses:course-autocomplete',
                attrs={'class': 'form-control'}
            ),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'min_total_score': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.1'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

class AskOraForm(forms.ModelForm):
    class Meta:
        model = AskOra
        fields = ['title','question_text','response_deadline']  # Menyesuaikan field dengan model AskOra
        
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'title '}),
            "question_text": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
                config_name="extends",
            ),
            #'question_text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Insert Question hare', 'rows': 4}),
            'response_deadline': forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Select response deadline', 'type': 'datetime-local'})
           
           
        }
        def clean_response_deadline(self):
            response_deadline = self.cleaned_data['response_deadline']
            if response_deadline < timezone.now():
                raise ValidationError("The response deadline cannot be in the past.")
            return response_deadline

#form re-runs
class CourseRerunForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_number', 'category', 'level', 'course_run']

    course_name_hidden = forms.CharField(required=False, widget=forms.HiddenInput())
    org_partner_hidden = forms.ModelChoiceField(queryset=Partner.objects.all(), required=False, widget=forms.HiddenInput())

    # Editable fields
    course_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 100%'}))  
    course_run = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 100%'}))

    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={'class': 'form-control', 'style': 'width: 100%'}))
    level = forms.ChoiceField(choices=[('basic', 'Basic'), ('middle', 'Middle'), ('advanced', 'Advanced')], widget=forms.Select(attrs={'class': 'form-control', 'style': 'width: 100%'}))



class CoursePriceForm(forms.ModelForm):
    class Meta:
        model = CoursePrice
        fields = ['partner_price', 'discount_percent', 'price_type']

        widgets = {
            'partner_price': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan harga...',
                'min': '0',
                'step': '0.01',
            }),
            'discount_percent': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan diskon...',
                'min': '0',
                'max': '100',
                'step': '0.01',
            }),
            'price_type': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        # Misal, non-partner tidak boleh edit harga & diskon
        if not getattr(self.user, 'is_partner', False):
            self.fields['partner_price'].disabled = True
            self.fields['discount_percent'].disabled = True

    def clean(self):
        cleaned_data = super().clean()
        price_type = cleaned_data.get('price_type')
        partner_price = cleaned_data.get('partner_price')
        discount = cleaned_data.get('discount_percent')

        if price_type and price_type.code == 'free':
            # Jika harga free, harga dan diskon otomatis 0
            cleaned_data['partner_price'] = Decimal('0.00')
            cleaned_data['discount_percent'] = Decimal('0.00')
        else:
            if partner_price is None or partner_price <= 0:
                self.add_error('partner_price', 'Harga wajib diisi dan harus lebih dari 0 untuk harga non-free.')

            if discount is None:
                cleaned_data['discount_percent'] = Decimal('0.00')
            elif discount < 0 or discount > 100:
                self.add_error('discount_percent', 'Diskon harus antara 0 dan 100.')

        return cleaned_data


class CourseInstructorForm(forms.ModelForm):
    instructor = forms.ModelChoiceField(
        queryset=Instructor.objects.none(),
        widget=autocomplete.ModelSelect2(url='courses:instructor-autocomplete'),  # Ganti widget jadi ModelSelect2 dengan URL autocomplete
        required=True,
    )

    class Meta:
        model = Course
        fields = ['instructor']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        if self.request and self.request.user.is_authenticated:
            user = self.request.user
            if user.is_superuser:
                self.fields['instructor'].queryset = Instructor.objects.all()
            elif hasattr(user, 'is_partner') and user.is_partner:
                self.fields['instructor'].queryset = Instructor.objects.filter(provider__user=user)
            elif hasattr(user, 'is_instructor') and user.is_instructor:
                self.fields['instructor'].queryset = Instructor.objects.none()

    def clean_instructor(self):
        instructor = self.cleaned_data.get('instructor')
        if not instructor:
            raise forms.ValidationError("Please select a valid instructor.")
        return instructor


class GradeRangeForm(forms.ModelForm):
    class Meta:
        model = GradeRange
        fields = ['name', 'min_grade', 'max_grade']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter name of assessment here',
                'class': 'form-control'
            }),
            'min_grade': forms.NumberInput(attrs={
                'placeholder': '0',
                'class': 'form-control',
                'type': 'number',
                'min': '0',  # Optional: Add minimum value
                'max': '100',  # Optional: Add maximum value
            }),
            'max_grade': forms.NumberInput(attrs={
                'placeholder': '0',
                'class': 'form-control',
                'type': 'number',
                'min': '0',  # Optional: Add minimum value
                'max': '100',  # Optional: Add maximum value
            }),
        }

class AssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment
        fields = ['name', 'weight', 'flag', 'duration_in_minutes']  # Menambahkan durasi
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter name of assessment here',
                'class': 'form-control'
            }),
            'weight': forms.NumberInput(attrs={
                'placeholder': '0',
                'class': 'form-control',
                'type': 'number',
                'min': '0',  # Optional: Add minimum value
                'max': '100',  # Optional: Add maximum value
            }),
            'duration_in_minutes': forms.NumberInput(attrs={
                'placeholder': 'Enter duration in minutes',
                'class': 'form-control',
                'type': 'number',
                'min': '0',  # Durasi tidak boleh negatif
            }),
        }
        labels = {
            'flag': 'Enable editor visual',  # Custom label for the flag field
        }
        help_texts = {
            'weight': 'Enter the weight of the assessment (a percentage, 0-100).',
            'duration_in_minutes': 'Enter the duration of the assessment in minutes. (e.g., 0, 5, 10, 30, 60, 120)'
        }

    def clean_weight(self):
        weight = self.cleaned_data.get('weight')
        
        if weight < 0 or weight > 100:
            raise forms.ValidationError("Weight must be between 0 and 100.")
        
        return weight

    def clean_duration_in_minutes(self):
        duration = self.cleaned_data.get('duration_in_minutes')
        
        if duration is None:
            raise forms.ValidationError("Duration cannot be empty.")
        if duration < 0:
            raise forms.ValidationError("Duration must be a non-negative number.")
        
        return duration

    def clean(self):
        cleaned_data = super().clean()
        weight = cleaned_data.get('weight')
        duration_in_minutes = cleaned_data.get('duration_in_minutes')
        
        # You could add additional cross-field validation here if needed
        
        return cleaned_data

class QuestionForm(forms.ModelForm):
    text = forms.CharField(required=True)  # Default field is optional

    class Meta:
        model = Question
        fields = ['text']

    def __init__(self, *args, **kwargs):
        # Extract the assessment object from kwargs
        assessment = kwargs.pop('assessment', None)
        super().__init__(*args, **kwargs)

        # Conditionally set widget based on the assessment flag
        if assessment and assessment.flag:
            self.fields['text'].widget = CKEditor5Widget("extends")  # CKEditor widget
        else:
            self.fields['text'].widget = forms.TextInput(attrs={'class': 'form-control'})  # Plain text widget
    
       
class ChoiceForm(forms.ModelForm):
    text = forms.CharField(required=True)  # Default field is optional

    class Meta:
        model = Choice
        fields = ['text', 'is_correct']

    def __init__(self, *args, **kwargs):
        # Extract the assessment object from kwargs
        assessment = kwargs.pop('assessment', None)
        super().__init__(*args, **kwargs)

        # Conditionally set widget based on the assessment flag
        if assessment and assessment.flag:
            self.fields['text'].widget = CKEditor5Widget("extends")  # CKEditor widget
        else:
            self.fields['text'].widget = forms.TextInput(attrs={'class': 'form-control'})  # Plain text widget
       
ChoiceFormSet = inlineformset_factory(
    Question,
    Choice,
    form=ChoiceForm,
    fields=['text', 'is_correct'],
    extra=1,
    can_delete=True
)
#add section
class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ['title','courses','parent']

class MatrialForm(forms.ModelForm):
    #description = forms.CharField(widget=CKEditor5Widget())
    class Meta:
        model = Material
        fields = ['title','description']
        widgets = {
            
            'title': forms.TextInput(attrs={'placeholder': 'Enter short title here', 'class': 'form-control'}),
            "description": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
                config_name="extends",
            ),
            #'description': CKEditor5Widget(attrs={'placeholder': 'Enter full description here', 'class': 'django_ckeditor_5'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            
        }

class ProfilForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['sort_description', 'description', 'image', 'link_video', 'hour', 'language', 'level', 'start_date', 'end_date', 'start_enrol', 'end_enrol']

        widgets = {
            'sort_description': forms.TextInput(attrs={'placeholder': 'Enter short description here', 'class': 'form-control'}),
            "description": CKEditor5Widget(attrs={"class": "django_ckeditor_5"}, config_name="extends"),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'link_video': forms.URLInput(attrs={'placeholder': 'Enter video URL here', 'class': 'form-control'}),
            'hour': forms.NumberInput(attrs={'class': 'form-control'}),
            'language': forms.Select(attrs={'class': 'form-control'}),
            'level': forms.Select(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'start_enrol': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_enrol': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(ProfilForm, self).__init__(*args, **kwargs)

    
def save(self, commit=True):
    course = super(ProfilForm, self).save(commit=False)

    if self.cleaned_data.get('image') and course.pk:
        old_course = Course.objects.get(pk=course.pk)
        old_image_path = old_course.image.name  # Simpan path lama
        if old_course.image != self.cleaned_data['image']:
            old_course.delete_old_image()
    else:
        old_image_path = None

    if self.cleaned_data.get('image'):
        image_file = self.cleaned_data['image']
        image = PILImage.open(image_file)

        image = image.resize((1200, 628), PILImage.Resampling.LANCZOS)
        image_io = io.BytesIO()
        image.save(image_io, format='WEBP', quality=100)
        image_io.seek(0)

        while image_io.tell() > 100 * 1024:
            image_io.seek(0)
            image.save(image_io, format='WEBP', quality=90)
            image_io.seek(0)

        # Gunakan nama dan path lama jika ada
        if old_image_path:
            base_dir = os.path.dirname(old_image_path)  # direktori lama
            new_image_name = os.path.splitext(os.path.basename(old_image_path))[0] + '.webp'
            final_path = os.path.join(base_dir, new_image_name)
        else:
            new_image_name = image_file.name.rsplit('.', 1)[0] + '.webp'
            final_path = new_image_name  # akan disimpan di path default

        webp_image_file = ContentFile(image_io.read(), name=final_path)
        course.image.save(webp_image_file.name, webp_image_file, save=False)

    if commit:
        course.save()

    return course
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_number', 'course_run', 'slug', 'category', 'level',  'org_partner']
       # fields = ['course_name', 'course_number', 'course_run', 'org_partner', 'instructor', 'status_course', 'description']
        
        widgets = {
            "course_name": forms.TextInput(attrs={
                "placeholder": "Full Stack Development",
                "class": "form-control",
                "oninput": "listingslug(value)"
            }),
           
            "slug": forms.HiddenInput(attrs={
                "class": "form-control",
                "maxlength": "200"
            }),
            "course_number": forms.TextInput(attrs={
                "placeholder": "CS201",
                "class": "form-control"
            }),
            "course_run": forms.TextInput(attrs={
                "placeholder": "2023",
                "class": "form-control"
            }),
            "org_partner": forms.Select(attrs={
                "class": "form-control js-example-basic-single",
                "id": "id_org_partner"
            }),
            "category": forms.Select(attrs={
                "class": "form-control js-example-basic-single"
            }),
            "level": forms.Select(attrs={
                "class": "form-control js-example-basic-single"
            })
        }
    
    def __init__(self, *args, **kwargs):

        user = kwargs.pop('user', None)  # Get the logged-in user from the view

        super().__init__(*args, **kwargs)


        if user:

            if user.is_superuser:

                # Admin: Show all partners in the dropdown

                self.fields['org_partner'].queryset = Partner.objects.all()
              
            elif user.is_partner:

                # Partner: Show only their own partner

                self.fields['org_partner'].queryset = Partner.objects.filter(user=user)
                
            elif user.is_instructor:

                # Instructor: Show only the partner they are associated with

                instructor = user.instructors.first()  # Get the first instructor instance

                if instructor:

                    self.fields['org_partner'].queryset = Partner.objects.filter(id=instructor.provider.id)
                    
                else:

                    self.fields['org_partner'].queryset = Partner.objects.none()  # No options if no instructor found

            else:

                # Optionally handle other user types or set a default queryset

                self.fields['org_partner'].queryset = Partner.objects.none()  # No options for other users
                


class PartnerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset=CustomUser.objects.none(),
        widget=autocomplete.ModelSelect2(
            url='courses:user-autocomplete',
            attrs={'class': 'form-control'}
        )
    )

    name = forms.ModelChoiceField(
        queryset=Universiti.objects.none(),
        widget=autocomplete.ModelSelect2(
            url='courses:universiti-autocomplete',
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = Partner
        fields = ['name', 'user', 'phone', 'tax', 'iceiprice', 'logo', 'address', 'description']
        widgets = {
            "phone": forms.TextInput(attrs={"placeholder": "Phone Number", "class": "form-control"}),
            "address": forms.Textarea(attrs={"placeholder": "Address", "class": "form-control"}),
            "description": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
                config_name="extends",
            ),
            "tax": forms.NumberInput(attrs={"placeholder": "Tax Number", "class": "form-control"}),
            "iceiprice": forms.NumberInput(attrs={"placeholder": "Ice Price %", "class": "form-control"}),
            "logo": forms.ClearableFileInput(attrs={'class': 'form-control', 'accept': 'image/*'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.pk:
            # Jika edit, batasi queryset supaya hanya bisa memilih instance yang terkait
            if self.instance.user:
                self.fields['user'].queryset = CustomUser.objects.filter(pk=self.instance.user.pk)
            if self.instance.name:
                self.fields['name'].queryset = Universiti.objects.filter(pk=self.instance.name.pk)
        else:
            # Jika create baru, isi queryset penuh agar pilihan valid
            self.fields['user'].queryset = CustomUser.objects.all()
            self.fields['name'].queryset = Universiti.objects.all()

    def clean_user(self):
        user_value = self.cleaned_data.get('user')
        
        if not user_value:
            raise forms.ValidationError("This field is required.")
        
        if Partner.objects.filter(user=user_value).exists() and (not self.instance.pk or self.instance.user != user_value):
            raise forms.ValidationError("This user already exists as a partner. Please choose another.")
        
        return user_value

    def save(self, commit=True):
        partner = super().save(commit=False)

        if self.instance.pk and self.instance.user != partner.user:
            old_user = self.instance.user
            if old_user:
                old_user.is_partner = False
                old_user.save()

        if partner.user:
            partner.user.is_partner = True
            partner.user.save()

        if commit:
            partner.save()

        return partner

    

#selfupdatepartner
def validate_optional_url(field_name, value):
    if value:
        validator = URLValidator()
        try:
            validator(value)
        except ValidationError:
            raise forms.ValidationError(f"URL untuk {field_name} tidak valid.")
    return value


# Styles reusable untuk input biasa
base_input_style = (
    'padding: 10px; '
    'border-radius: 8px; '
    'border: 1.5px solid #ccc; '
    'box-shadow: 1px 1px 5px rgba(0,0,0,0.05); '
    'transition: border-color 0.3s ease;'
)
base_onfocus = "this.style.borderColor='#007bff'; this.style.boxShadow='0 0 5px #007bff';"
base_onblur = "this.style.borderColor='#ccc'; this.style.boxShadow='1px 1px 5px rgba(0,0,0,0.05)';"

personal_data_widgets = {
    'phone': forms.TextInput(attrs={
        'placeholder': 'Phone Number',
        'class': 'form-control',
        'style': f'width: 300px; {base_input_style}',
        'maxlength': '15',
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    'address': forms.Textarea(attrs={
        'placeholder': 'Address',
        'class': 'form-control',
        'rows': 3,
        'style': (
            'border-radius: 8px; padding: 10px; border: 1.5px solid #ccc; '
            'box-shadow: 1px 1px 5px rgba(0,0,0,0.05); transition: border-color 0.3s ease; resize:none;'
        ),
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    
}

bank_info_widgets = {
    'account_number': forms.TextInput(attrs={
        'placeholder': 'Account Number',
        'class': 'form-control',
        'style': f'width: 250px; {base_input_style}',
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    'account_holder_name': forms.TextInput(attrs={
        'placeholder': 'Account Holder Name',
        'class': 'form-control',
        'style': f'width: 400px; {base_input_style}',
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    'bank_name': forms.TextInput(attrs={
        'placeholder': 'Bank Name',
        'class': 'form-control',
        'style': f'width: 300px; {base_input_style}',
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    'payment_method': forms.Select(attrs={
        'class': 'form-control',
        'style': f'width: 300px; {base_input_style}',
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    'logo': forms.ClearableFileInput(attrs={
        'class': 'form-control-file',
        'accept': 'image/*',
        'style': 'margin-top: 8px;'
    }),
}

tax_info_widgets = {
    'is_pkp': forms.CheckboxInput(attrs={
        'class': 'form-check-input',
        'style': 'transform: scale(1.3); margin-left: 5px;',
    }),
    'npwp': forms.TextInput(attrs={
        'placeholder': 'NPWP',
        'class': 'form-control',
        'style': f'width: 300px; {base_input_style}',
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    }),
    'npwp_file': forms.ClearableFileInput(attrs={
        'class': 'form-control-file',
        'accept': 'image/*',
        'style': 'margin-top: 8px;'
    }),
}

social_media_widgets = {}
for network in ['tiktok', 'youtube', 'twitter', 'facebook']:
    social_media_widgets[network] = forms.URLInput(attrs={
        'placeholder': f'{network.capitalize()} URL',
        'class': 'form-control',
        'style': base_input_style,
        'onfocus': base_onfocus,
        'onblur': base_onblur,
    })

# Gabungkan semua
widgets = {}
widgets.update(personal_data_widgets)
widgets.update(bank_info_widgets)
widgets.update(tax_info_widgets)
widgets.update(social_media_widgets)


class PartnerFormUpdate(forms.ModelForm):
    description = forms.CharField(widget=CKEditor5Widget())
    class Meta:
        model = Partner
        fields = [
            'account_number', 'account_holder_name','bank_name','phone','is_pkp','npwp','npwp_file','payment_method','logo', 'address', 'description', 
              
            'tiktok', 'youtube', 'twitter', 'facebook'
        ]

        widgets = widgets
    def clean_account_number(self):
        value = self.cleaned_data.get('account_number')
        if value and not value.isdigit():
            raise forms.ValidationError("Nomor rekening hanya boleh berupa angka.")
        return value

    def clean_npwp(self):
        value = self.cleaned_data.get('npwp')
        if value:
            npwp_cleaned = value.replace('.', '').replace('-', '').replace(' ', '')
            if not re.fullmatch(r'\d{15}', npwp_cleaned):
                raise forms.ValidationError("NPWP harus terdiri dari 15 digit angka.")
        return value

    def clean_npwp_file(self):
        file = self.cleaned_data.get('npwp_file')
        if file:
            if file.size > 2 * 1024 * 1024:
                raise forms.ValidationError("Ukuran file maksimal 2MB.")
            if not file.content_type in ['application/pdf', 'image/jpeg', 'image/png']:
                raise forms.ValidationError("Format file harus PDF, JPG, atau PNG.")
        return file

    def clean_phone(self):
        value = self.cleaned_data.get('phone')
        if value and not re.match(r'^\+?\d{8,15}$', value):
            raise forms.ValidationError("Format nomor telepon tidak valid. Gunakan format internasional seperti +628123456789.")
        return value

    def clean_tiktok(self):
        return validate_optional_url("TikTok", self.cleaned_data.get('tiktok'))

    def clean_youtube(self):
        return validate_optional_url("YouTube", self.cleaned_data.get('youtube'))

    def clean_twitter(self):
        return validate_optional_url("Twitter", self.cleaned_data.get('twitter'))

    def clean_facebook(self):
        return validate_optional_url("Facebook", self.cleaned_data.get('facebook'))

class InstructorForm(forms.ModelForm):
    expertise = forms.CharField(
        widget=CKEditor5Widget(),  # atau CKEditorWidget()
        required=False  # jangan required di browser, validasi manual di Python
    )

    class Meta:
        model = Instructor
        fields = ['bio', 'expertise', 'experience_years', 'provider', 'agreement', 'tech']
        labels = {
            'bio': 'Tell us about yourself',
            'expertise': 'Your Area of Expertise',
            'experience_years': 'Years of Experience',
            'provider': 'Select Your Institution',
            'tech': 'Technology Stack (URL)',
            'agreement': 'I agree to the terms and conditions',
        }
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'experience_years': forms.NumberInput(attrs={'class': 'form-control'}),
            'provider': forms.Select(attrs={'class': 'form-control select2', 'required': 'True'}),
            'tech': forms.URLInput(attrs={'class': 'form-control', 'required': 'True'}),
            'agreement': forms.CheckboxInput(attrs={'class': 'form-check-input', 'required': 'True'}),
        }

    def clean_experience_years(self):
        experience = self.cleaned_data.get('experience_years')
        if experience is not None and experience < 0:
            raise forms.ValidationError("Experience years cannot be negative.")
        return experience

    def clean_expertise(self):
        data = self.cleaned_data.get('expertise')
        if not data or len(data.strip()) < 10:
            raise forms.ValidationError("Please provide at least 10 characters for your expertise.")
        return data
    
#instructor add coruse
class InstructorAddCoruseForm(forms.ModelForm):

    class Meta:

        model = Course

        fields = ['instructor']

        widgets = {

            'instructor': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Enter instructor name'}),

        }



class TeamMemberForm(forms.ModelForm):

    email = forms.EmailField(required=True)  # Add an email field


    class Meta:

        model = TeamMember

        fields = ['email']  # Include only the email field
        widgets = {

            'email': forms.TextInput(attrs={

                'class': 'form-control',  # Bootstrap class for styling

                'placeholder': 'Enter instructor email',  # Placeholder text

                'required': 'required'  # Make the field required

            }),

        }

    def __init__(self, *args, **kwargs):

        super(TeamMemberForm, self).__init__(*args, **kwargs)

        self.fields['email'].queryset = CustomUser.objects.all()  # Limit user choices if needed


    def clean_email(self):

        email = self.cleaned_data.get('email')

        if not CustomUser.objects.filter(email=email).exists():

            raise forms.ValidationError("No user found with this email.")

        return email